### PR TITLE
Added payload queueing

### PR DESCRIPTION
**Pull request by ffxsam**
This was sometimes an issue, where I'd get a warning saying I couldn't dispatch a payload because a dispatch was already in progress. But to just ignore it, IMO, was unacceptable.. what if it was some critical operation? So I added queueing so dispatches are never discarded.

### CODE REVIEW

**Comment by luisherranz** [comment]
I think queueing can be a good idea if you have multiple async API calls coming back at the same time, but only in that case.

Queueing to avoid the error _"You cannot dispatch in the middle of another dispatch."_ will void one of the core principles of Flux which is precisely **"One action should never trigger another action"**.

When you find yourself in that case, you have to refactor your code and make it simpler: i.e.: the things which happen in the second action should happen in the first action instead.

Could you please share an example about when is this happening?

**Comment by ffxsam** [comment]
Good point. To clarify, in this situation, one action is not triggering another. It's just that one action is not yet complete when the next one is dispatched. Where I'm running into this problem is an OAuth action, followed immediately by an action to trigger a DB query. Apparently they're not sequential, and they overlap for some reason.

But I can see where this is going. :) The solution would be to figure out how to only call the query once OAuth is fully complete.

**Comment by luisherranz** [comment]
Looks like an async case. Flux flow should be synchronous, did you take a look at the [Async Operations](https://github.com/worona/meteorflux/tree/devel/packages/dispatcher#async-operations)?
Maybe the oauth call shouldn't be started by a dispatch.

**Comment by ffxsam** [comment]
Yeah, that does make sense. Ok, I'll rework the code, and we can just pitch this fork. (no pun intended) Thanks!

**Comment by luisherranz** [comment]
No problem. Queueing can be interesting for multiple async API calls coming back at the same time, but I am not sure if that's the case in Meteor. I will keep this PR in mind just in case.

Thanks for your contribution @ffxsam!

**Comment by ffxsam** [comment]
You know, I was thinking.. it would at least be great if the warning message showed which action was being dispatched. It would greatly help with debugging.

**Comment by luisherranz** [comment]
Sure, that would be a good addition.

**Pull request closed without merging**
